### ISSUE TITLE
General Roadmap

### ISSUE THREAD

**Issue by chamons** [xamarin/binding-tools-for-swift#165]
Welcome to Binding Tools for Swift (BTFS)!

While much of the infrastructure and binding tooling is complete, there is number of items we expect to work on before integrating with Xamarin.iOS and Mac.

In no particular order:

- [ ] Project and MSBuild support to make it easier to use
- [ ] Support for Protocols with Associated Types
- [ ] Support for Swift 5.1
- [ ] Support for non-escaping closures
- [ ] Support for closures in bound generic types
- [ ] Improving documentation and samples

**Comment by thisisthekap** [comment]
@chamons What is the current state concerning the roadmap? Are you able to provide any ETA when BTFS is going to be available/usable as preview or final release?

**Comment by chamons** [comment]
I've been reassigned to another team. @dalexsoto or @stephen-hawley may have more information for you.
